DROP DATABASE IF EXISTS cbr WITH (FORCE);
CREATE DATABASE cbr;

\c cbr;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS boats (
    id SERIAL PRIMARY KEY,
    serialnum VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    images JSONB NOT NULL,
    tags JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);